// All interface icons use MingCute Core Regular.
export {
  ArrowRightUpRegular as ArrowUpRight,
  ArrowRightRegular as ArrowRight,
  ArrowUpRegular as ArrowUp,
  Book2Regular as BookOpen,
  LayersRegular as Layers,
  CheckRegular as Check,
  DownRegular as ChevronDown,
  LeftRegular as ChevronLeft,
  RightRegular as ChevronRight,
  UploadRegular as Upload,
  FileRegular as FileText,
  CloseRegular as X,
  MenuRegular as Menu,
  Refresh2Regular as RotateCw,
  CheckCircleRegular as CheckCircle2,
  LightningRegular as Zap,
  CursorRegular as MousePointer2,
  PauseRegular as Pause,
  PlayRegular as Play,
  Home2Regular as Home,
  ChartBarRegular as Chart,
  FlameRegular as Flame,
  SearchRegular as Search,
  Settings3Regular as Settings,
  SunRegular as Sun,
} from '@mingcute/react/core-regular';
