import Icon from './Icon'
import './AnswerReview.css'

const ArrowIcon = () => <Icon name="arrow" />

export default function Practice({ practice, mcqAnswers, setMcqAnswers, gapAnswers, setGapAnswers, theoryAnswers, setTheoryAnswers, result, setResult, isSubmitting, submitPractice }) {
  const hasCompleteGradableAnswers = practice.mcqs.every((_, index) => mcqAnswers[index]) && practice.fill_in_the_gaps.every((_, index) => gapAnswers[index]?.trim())
  return <section className="quiz"><fieldset className="practice-fields" disabled={isSubmitting}><legend className="sr-only">Mixed practice answers</legend>
      <div className="quiz-heading"><div><p className="eyebrow">Mixed practice</p><h1>{practice.title}</h1><p>Answer the objective questions first, then use the theory prompts to deepen your recall.</p></div><div className="progress-note"><span>{practice.mcqs.length + practice.fill_in_the_gaps.length}</span><small>gradable<br />answers</small></div></div>
      {practice.coverage_note && <p className="source-reminder">{practice.coverage_note}</p>}{practice.source_batches?.length > 0 && <p className="source-reminder">Source sections supplied: {[...new Set(practice.source_batches.flatMap(batch => batch.sections))].join(", ")}. This records batch inputs, not verified question citations.</p>}<h2 className="section-title">Objective practice</h2>
      {practice.mcqs.map((q, i) => <article key={`m${i}`}><small>Question {i + 1} of {practice.mcqs.length}</small><h3>{q.question}</h3>{q.options.map(o => <button aria-pressed={mcqAnswers[i] === o.label} className={mcqAnswers[i] === o.label ? 'selected' : ''} key={o.label} onClick={() => { setMcqAnswers({ ...mcqAnswers, [i]: o.label }); setResult() }}><b>{o.label}</b><span>{o.text}</span></button>)}</article>)}
      <h2 className="section-title">Keyword recall</h2>
      {practice.fill_in_the_gaps.map((q, i) => <article key={`g${i}`}><small>Fill the gap {i + 1} of {practice.fill_in_the_gaps.length}</small><h3>{q.prompt}</h3><label className="sr-only" htmlFor={`gap-${i}`}>Answer for gap {i + 1}</label><input id={`gap-${i}`} value={gapAnswers[i] || ''} onChange={e => { setGapAnswers({ ...gapAnswers, [i]: e.target.value }); setResult() }} placeholder="Type the missing keyword" /></article>)}
      {practice.mcqs.length + practice.fill_in_the_gaps.length > 0 && <div className="submit-area"><button className="primary" disabled={!hasCompleteGradableAnswers || isSubmitting} onClick={submitPractice}>{isSubmitting ? 'Checking answers…' : 'Check objective answers'}<ArrowIcon /></button>{!hasCompleteGradableAnswers && <p>Complete all {practice.mcqs.length + practice.fill_in_the_gaps.length} gradable answers to see your score.</p>}</div>}
      {result && <><section className="score" role="status" aria-live="polite"><p className="eyebrow">Objective practice score</p><h2>{result.percentage}%</h2><p>{result.correct_mcqs} of {practice.mcqs.length} mcqs correct <span>·</span> {result.correct_gaps} of {practice.fill_in_the_gaps.length} keyword gaps correct</p><p className="score-note">{result.correct_mcqs + result.correct_gaps} of {result.total_gradable} gradable answers correct</p></section><section className="answer-review" aria-labelledby="answer-review-title"><div><p className="eyebrow">Review your answers</p><h2 id="answer-review-title">Learn from each answer</h2></div><h3>Multiple choice</h3>{practice.mcqs.map((q, i) => { const feedback = result.mcq_feedback?.[i]; return feedback && <article className={feedback.is_correct ? 'answer-correct' : 'answer-incorrect'} key={`mf${i}`}><small>Question {i + 1} · {feedback.is_correct ? 'Correct' : 'Review'}</small><h4>{q.question}</h4><p><b>Correct answer:</b> {feedback.correct_option}. {feedback.correct_answer}</p>{!feedback.is_correct && <p><b>Your answer:</b> {feedback.selected_option}. {q.options.find(option => option.label === feedback.selected_option)?.text}</p>}<p className="answer-explanation">{feedback.explanation}</p></article> })}<h3>Keyword recall</h3>{practice.fill_in_the_gaps.map((q, i) => { const feedback = result.gap_feedback?.[i]; return feedback && <article className={feedback.is_correct ? 'answer-correct' : 'answer-incorrect'} key={`gf${i}`}><small>Gap {i + 1} · {feedback.is_correct ? 'Correct' : 'Review'}</small><h4>{q.prompt}</h4><p><b>Expected keyword:</b> {feedback.expected_answer}</p>{!feedback.is_correct && <p><b>Your answer:</b> {feedback.submitted_answer}</p>}</article> })}</section></>}
      <h2 className="section-title theory-title">Theory practice</h2>
      <p className="section-description">Use these prompts for active recall. Your written answers are not included in the objective score.</p>
      {practice.theory_questions.map((q, i) => <article key={`t${i}`}><small>Theory prompt {i + 1} of {practice.theory_questions.length}</small><h3>{q.prompt}</h3><label className="sr-only" htmlFor={`theory-${i}`}>Theory answer {i + 1}</label><textarea id={`theory-${i}`} value={theoryAnswers[i] || ''} onChange={e => setTheoryAnswers({ ...theoryAnswers, [i]: e.target.value })} placeholder="Write your answer in your own words" /><details><summary>Self-review criteria</summary><p>{q.marking_guidance}</p></details></article>)}
    </fieldset></section>
}
